server:
  build: ./empire
  command: server -automigrate=true
  links:
    - postgres:postgres
  ports:
    - "8080:8080"
  volumes:
    - ~/.dockercfg:/root/.dockercfg
  env_file: .env
  user: root
  environment:
    EMPIRE_DATABASE_URL: postgres://postgres:postgres@postgres/postgres?sslmode=disable
    DOCKER_HOST:
postgres:
  image: postgres
