server:
  build: .
  command: server -automigrate=true
  links:
    - db:db
    - tracer:dockerhost
  ports:
    - "8080:8080"
  volumes:
    - ~/.dockercfg:/root/.dockercfg
    - "/var/run/docker.sock:/var/run/docker.sock"
  env_file: .env
  user: root
  environment:
    EMPIRE_DATABASE_URL: postgres://postgres:postgres@db/postgres?sslmode=disable
    DOCKER_HOST: unix:///var/run/docker.sock
    EMPIRE_X_SHOW_ATTACHED: 'true'
db:
  image: postgres
tracer:
  build: ./tracer
  env_file: .env
  environment:
    DD_BIND_HOST: "0.0.0.0"
