site_name: Empire Documentation
theme: readthedocs
pages:
  - 'Introduction': 'index.md'
  - Overview:
    - "Features & Design Goals - TODO": "features_and_design_goals.md"
    - "Known Limitations": "known_limitations.md"
    - "Roadmap - TODO": "roadmap.md"
    - "FAQ - TODO": "faq.md"
  - Getting Started:
    - "Prerequisites - TODO": "prerequisites.md"
    - "Quickstart: Installing": "quickstart_installing.md"
    - "Quickstart: Using": "quickstart_using.md"
    - "Production Best Practices - WIP": "production_best_practices.md"
  - Users Guide:
    - "Deploying an Application": "deploying_an_application.md"
    - "Process Management - TODO": "process_management.md"
    - "Exposing an app publicly": "exposing_an_app_publicly.md"
    - "SSL Certs": "ssl_certs.md"
    - "Activate log streaming": "log_streaming.md"
  - Hacking on Empire:
    - "Running Tests - TODO": "running_tests.md"
    - "Running Empire Locally - TODO": "running_empire_locally.md"
    - "Contribution Guidelines & Bug Reporting": "contributing.md"
    - "Reporting Security Vulnerabilities - TODO": "reporting_security_vulnerabilities.md"
  - Reference:
    - "Configuration": "configuration.md"
    - "Command Line - TODO": "command_line.md"
    - "Troubleshooting": "troubleshooting.md"


