# -------
# General
# -------

[hekad]
maxprocs = 4

[DashboardOutput]
address = ":4352"
ticker_interval = 15

# ------
# Inputs
# ------

[DockerLogInput]

# --------
# Decoders
# --------

# -------
# Filters
# -------

[docker_syslog_filter]
type = "SandboxFilter"
message_matcher = "Fields[ContainerName] != 'empire-logger'"
filename = "lua_filters/docker_syslog.lua"
ticker_interval = 60
preserve_data = true

[docker_syslog_filter.config]
max_buffer_size = 100

# --------
# Encoders
# --------

[PayloadEncoder]
append_newlines = false

# -------
# Outputs
# -------

# Log docker container logs to stdout. Useful for debugging.
[output_buffered_syslog]
type = "LogOutput"
message_matcher = "Type == 'heka.sandbox-output' && Fields[payload_type] == 'syslog'"
encoder = "PayloadEncoder"

# Sumologic output
[sumologic]
type = "HttpOutput"
message_matcher = "Type == 'heka.sandbox-output' && Fields[payload_type] == 'syslog'"
address = "%ENV[SUMOLOGIC_URL]"
encoder = "PayloadEncoder"

# Librato l2met output
[librato_l2met]
type = "HttpOutput"
message_matcher = "Type == 'heka.sandbox-output' && Fields[payload_type] == 'syslog'"
address = "%ENV[LIBRATO_URL]"
encoder = "PayloadEncoder"
