# -------
# General
# -------

[hekad]
maxprocs = 4

[DashboardOutput]
address = ":4352"
ticker_interval = 15

# ------
# Inputs
# ------

[DockerLogInput]
endpoint = "%ENV[DOCKER_HOST]"

[MemStatsInput]
type = "FilePollingInput"
ticker_interval = 20
file_path = "/proc/meminfo"
decoder = "MemStatsDecoder"

# --------
# Decoders
# --------

[MemStatsDecoder]
type = "SandboxDecoder"
filename = "lua_decoders/linux_memstats.lua"

# -------
# Filters
# -------

[DockerSyslogFilter]
type = "SandboxFilter"
message_matcher = "Fields[ContainerID] != '%ENV[CONTAINER_ID]'"
filename = "lua_filters/docker_syslog.lua"
ticker_interval = 1
preserve_data = true

[BufferedFilter]
type = "SandboxFilter"
message_matcher = "Type == 'heka.sandbox-output' && Fields[payload_type] == 'syslog'"
filename = "lua_filters/buffered_syslog.lua"
ticker_interval = 60
preserve_data = true
  
  [BufferedFilter.config]
  max_buffer_size = 100

[MemStatsFilter]
type = "SandboxFilter"
message_matcher = "Type == 'stats.memstats'"
filename = "lua_filters/memstats.lua"
ticker_interval = 20
preserve_data = true

# --------
# Encoders
# --------

[PayloadEncoder]
append_newlines = false

[CbufLibratoEncoder]
type = "SandboxEncoder"
filename = "lua_encoders/cbuf_librato.lua"
preserve_data = true

# -------
# Outputs
# -------

# Log docker container logs to stdout. Useful for debugging.
[DockerSyslogOutput]
type = "LogOutput"
message_matcher = "Type == 'heka.sandbox-output' && Fields[payload_type] == 'syslog'"
encoder = "PayloadEncoder"

# Sumologic output
[SumologicOutput]
type = "UdpOutput"
message_matcher = "Type == 'heka.sandbox-output' && Fields[payload_type] == 'syslog'"
address = "%ENV[SUMOLOGIC_URL]"
encoder = "PayloadEncoder"

# Librato l2met output
[LibratoL2metOutput]
type = "HttpOutput"
message_matcher = "Type == 'heka.sandbox-output' && Fields[payload_type] == 'buffered_syslog'"
address = "%ENV[LIBRATO_L2MET_URL]"
username = "%ENV[LIBRATO_L2MET_TOKEN]"
password = ""
encoder = "PayloadEncoder"

# Librato Circular Buffer output
[LibratoOutput]
type = "HttpOutput"
message_matcher = "Type == 'heka.sandbox-output' && Fields[payload_type] == 'cbuf'"
encoder = "CbufLibratoEncoder"
address = "https://metrics-api.librato.com/v1/metrics"
username = "%ENV[LIBRATO_USER]"
password = "%ENV[LIBRATO_TOKEN]"
  [LibratoOutput.headers]
  Content-Type = ["application/json"]
